use chrono::{Duration, Local, NaiveDate, TimeZone};
use rusqlite::{Connection, OpenFlags};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

mod performance;
pub use performance::RecentPerformance;

const GEMINI_DIR: &str = ".gemini";
const ANTIGRAVITY_PREFIX: &str = "antigravity";
const TOKEN_ARCHIVE_DIR: &str = "antigravity";
const TOKEN_ARCHIVE_FILE: &str = "token_usage_archive.db";
const MAX_GENERATION_BLOB_BYTES: i64 = 64 * 1024 * 1024;
const GENERATION_STEP_TYPE: i64 = 15;

/// A compact, read-only summary of the token accounting records generated by Antigravity.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct LocalTokenTotals {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cached_tokens: u64,
    pub total_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTokenDaily {
    pub date: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cached_tokens: u64,
    pub total_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTokenHourly {
    pub hour: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cached_tokens: u64,
    pub total_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTokenModel {
    pub model: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cached_tokens: u64,
    pub total_tokens: u64,
    pub request_count: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTokenUsageSummary {
    pub recent_performance: Option<RecentPerformance>,
    pub today: LocalTokenTotals,
    pub yesterday: LocalTokenTotals,
    pub last_3_days: LocalTokenTotals,
    pub last_7_days: LocalTokenTotals,
    pub last_30_days: LocalTokenTotals,
    pub daily: Vec<LocalTokenDaily>,
    pub hourly: Vec<LocalTokenHourly>,
    /// Model totals for today. `by_model` remains the 30-day view for compatibility.
    pub by_model_today: Vec<LocalTokenModel>,
    /// Model totals for yesterday.
    pub by_model_yesterday: Vec<LocalTokenModel>,
    /// Model totals for the last 3 days.
    pub by_model_3_days: Vec<LocalTokenModel>,
    /// Model totals for the last 7 days.
    pub by_model_7_days: Vec<LocalTokenModel>,
    /// Model totals for the last 30 days.
    pub by_model: Vec<LocalTokenModel>,
    pub databases_scanned: u64,
    pub generations_scanned: u64,
    pub skipped_large_records: u64,
    pub unreadable_databases: u64,
    pub last_activity: Option<i64>,
    pub generated_at: i64,
}

#[derive(Debug, Clone)]
struct GenerationEvent {
    model: String,
    input_tokens: u64,
    output_tokens: u64,
    cached_tokens: u64,
    total_tokens: u64,
    timestamp_seconds: i64,
}

#[derive(Debug, Clone, Copy)]
enum WireValue<'a> {
    Varint(u64),
    Bytes(&'a [u8]),
}

/// Scan native Antigravity conversation stores without changing them.
pub fn get_local_token_usage() -> Result<LocalTokenUsageSummary, String> {
    let now = Local::now();
    let today = now.date_naive();
    let start_30_days = today - Duration::days(29);
    let database_paths = discover_database_files()?;
    let live_source_keys = database_paths
        .iter()
        .map(|path| source_key_for_database(path))
        .collect::<HashSet<_>>();

    let mut events = Vec::new();
    let mut performance_samples = Vec::new();
    let mut scanned_sources = HashSet::new();
    let mut generations_scanned = 0_u64;
    let mut skipped_large_records = 0_u64;
    let mut unreadable_databases = 0_u64;

    let archive_path = token_archive_path()?;
    let archived = if archive_path.is_file() {
        match scan_archive(&archive_path, start_30_days, &live_source_keys) {
            Ok(result) => result,
            Err(error) => {
                unreadable_databases += 1;
                crate::modules::logger::log_warn(&format!(
                    "无法读取本地 Token 归档 {}: {}",
                    archive_path.display(),
                    error
                ));
                ArchivedTokenData::default()
            }
        }
    } else {
        ArchivedTokenData::default()
    };

    scanned_sources.extend(archived.source_keys.iter().cloned());
    generations_scanned += archived.generations_scanned;
    skipped_large_records += archived.skipped_large_records;
    events.extend(archived.events.iter().cloned());

    for path in &database_paths {
        let source_key = source_key_for_database(path);
        scanned_sources.insert(source_key.clone());
        let archived_ids = archived
            .generation_ids_by_source
            .get(&source_key)
            .cloned()
            .unwrap_or_default();
        match scan_database(path, start_30_days, &archived_ids) {
            Ok(result) => {
                generations_scanned += result.generations_scanned;
                skipped_large_records += result.skipped_large_records;
                events.extend(result.events);
                performance_samples.extend(result.performance_samples);
            }
            Err(error) => {
                unreadable_databases += 1;
                crate::modules::logger::log_warn(&format!(
                    "无法读取 Antigravity 本地 Token 数据库 {}: {}",
                    path.display(),
                    error
                ));
            }
        }
    }

    events.sort_by_key(|event| event.timestamp_seconds);

    let yesterday = today - Duration::days(1);
    let mut today_totals = LocalTokenTotals::default();
    let mut yesterday_totals = LocalTokenTotals::default();
    let mut last_3_days_totals = LocalTokenTotals::default();
    let mut last_7_days_totals = LocalTokenTotals::default();
    let mut last_30_days_totals = LocalTokenTotals::default();
    let mut daily: BTreeMap<NaiveDate, LocalTokenTotals> = BTreeMap::new();
    let mut hourly: BTreeMap<String, LocalTokenTotals> = BTreeMap::new();
    let mut by_model_today: BTreeMap<String, LocalTokenTotals> = BTreeMap::new();
    let mut by_model_yesterday: BTreeMap<String, LocalTokenTotals> = BTreeMap::new();
    let mut by_model_3_days: BTreeMap<String, LocalTokenTotals> = BTreeMap::new();
    let mut by_model_7_days: BTreeMap<String, LocalTokenTotals> = BTreeMap::new();
    let mut by_model_30_days: BTreeMap<String, LocalTokenTotals> = BTreeMap::new();
    let mut last_activity = None;

    for event in events {
        let Some(date_time) = Local.timestamp_opt(event.timestamp_seconds, 0).single() else {
            continue;
        };
        let date = date_time.date_naive();
        let hour = date_time.format("%Y-%m-%d %H:00").to_string();

        add_event(&mut last_30_days_totals, &event);
        add_event(daily.entry(date).or_default(), &event);
        add_event(hourly.entry(hour).or_default(), &event);
        add_event(
            by_model_30_days.entry(event.model.clone()).or_default(),
            &event,
        );

        if date == today {
            add_event(&mut today_totals, &event);
            add_event(
                by_model_today.entry(event.model.clone()).or_default(),
                &event,
            );
        }
        if date == yesterday {
            add_event(&mut yesterday_totals, &event);
            add_event(
                by_model_yesterday.entry(event.model.clone()).or_default(),
                &event,
            );
        }
        if is_within_last_days(date, today, 3) {
            add_event(&mut last_3_days_totals, &event);
            add_event(
                by_model_3_days.entry(event.model.clone()).or_default(),
                &event,
            );
        }
        if is_within_last_days(date, today, 7) {
            add_event(&mut last_7_days_totals, &event);
            add_event(
                by_model_7_days.entry(event.model.clone()).or_default(),
                &event,
            );
        }
        last_activity = Some(
            last_activity.map_or(event.timestamp_seconds, |current: i64| {
                current.max(event.timestamp_seconds)
            }),
        );
    }

    let daily = daily
        .into_iter()
        .map(|(date, totals)| LocalTokenDaily {
            date: date.format("%Y-%m-%d").to_string(),
            input_tokens: totals.input_tokens,
            output_tokens: totals.output_tokens,
            cached_tokens: totals.cached_tokens,
            total_tokens: totals.total_tokens,
            request_count: totals.request_count,
        })
        .collect();

    let hourly = hourly
        .into_iter()
        .map(|(hour, totals)| LocalTokenHourly {
            hour,
            input_tokens: totals.input_tokens,
            output_tokens: totals.output_tokens,
            cached_tokens: totals.cached_tokens,
            total_tokens: totals.total_tokens,
            request_count: totals.request_count,
        })
        .collect();

    Ok(LocalTokenUsageSummary {
        recent_performance: performance::summarize(performance_samples, now.timestamp()),
        today: today_totals,
        yesterday: yesterday_totals,
        last_3_days: last_3_days_totals,
        last_7_days: last_7_days_totals,
        last_30_days: last_30_days_totals,
        daily,
        hourly,
        by_model_today: model_totals(by_model_today),
        by_model_yesterday: model_totals(by_model_yesterday),
        by_model_3_days: model_totals(by_model_3_days),
        by_model_7_days: model_totals(by_model_7_days),
        by_model: model_totals(by_model_30_days),
        databases_scanned: scanned_sources.len() as u64,
        generations_scanned,
        skipped_large_records,
        unreadable_databases,
        last_activity,
        generated_at: now.timestamp(),
    })
}

fn model_totals(by_model: BTreeMap<String, LocalTokenTotals>) -> Vec<LocalTokenModel> {
    let mut models: Vec<LocalTokenModel> = by_model
        .into_iter()
        .map(|(model, totals)| LocalTokenModel {
            model,
            input_tokens: totals.input_tokens,
            output_tokens: totals.output_tokens,
            cached_tokens: totals.cached_tokens,
            total_tokens: totals.total_tokens,
            request_count: totals.request_count,
        })
        .collect();
    models.sort_by(|left, right| {
        right
            .total_tokens
            .cmp(&left.total_tokens)
            .then_with(|| left.model.cmp(&right.model))
    });
    models
}

fn add_event(totals: &mut LocalTokenTotals, event: &GenerationEvent) {
    totals.input_tokens = totals.input_tokens.saturating_add(event.input_tokens);
    totals.output_tokens = totals.output_tokens.saturating_add(event.output_tokens);
    totals.cached_tokens = totals.cached_tokens.saturating_add(event.cached_tokens);
    totals.total_tokens = totals.total_tokens.saturating_add(event.total_tokens);
    totals.request_count = totals.request_count.saturating_add(1);
}

fn is_within_last_days(date: NaiveDate, today: NaiveDate, days: i64) -> bool {
    days > 0 && date >= today - Duration::days(days - 1) && date <= today
}

struct DatabaseScanResult {
    events: Vec<GenerationEvent>,
    performance_samples: Vec<performance::Sample>,
    generations_scanned: u64,
    skipped_large_records: u64,
}

#[derive(Default)]
struct ArchivedTokenData {
    events: Vec<GenerationEvent>,
    source_keys: HashSet<String>,
    generation_ids_by_source: HashMap<String, HashSet<i64>>,
    generations_scanned: u64,
    skipped_large_records: u64,
}

fn token_archive_path() -> Result<PathBuf, String> {
    let Some(home) = dirs::home_dir() else {
        return Err("无法定位用户目录".to_string());
    };
    Ok(home
        .join(GEMINI_DIR)
        .join(TOKEN_ARCHIVE_DIR)
        .join(TOKEN_ARCHIVE_FILE))
}

fn source_key_for_database(path: &Path) -> String {
    let Some(home) = dirs::home_dir() else {
        return path.to_string_lossy().replace('\\', "/");
    };
    let gemini_home = home.join(GEMINI_DIR);
    let gemini_home = fs::canonicalize(&gemini_home).unwrap_or(gemini_home);
    let path = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    path.strip_prefix(&gemini_home)
        .map(|relative| {
            relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/")
        })
        .unwrap_or_else(|_| path.to_string_lossy().replace('\\', "/"))
}

fn scan_archive(
    path: &Path,
    since: NaiveDate,
    live_source_keys: &HashSet<String>,
) -> Result<ArchivedTokenData, String> {
    let connection = Connection::open_with_flags(path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .map_err(|error| error.to_string())?;
    connection
        .busy_timeout(std::time::Duration::from_secs(2))
        .map_err(|error| error.to_string())?;

    let mut result = ArchivedTokenData::default();
    let mut source_statement = connection
        .prepare("SELECT source_key FROM archived_sources")
        .map_err(|error| error.to_string())?;
    let source_rows = source_statement
        .query_map([], |row| row.get::<_, String>(0))
        .map_err(|error| error.to_string())?;
    for source in source_rows {
        result
            .source_keys
            .insert(source.map_err(|error| error.to_string())?);
    }

    let mut statement = connection
        .prepare(
            "SELECT source_key, generation_idx, model, input_tokens, output_tokens,
                    cached_tokens, total_tokens, timestamp_seconds, valid, oversized
             FROM archived_generations
             ORDER BY source_key, generation_idx",
        )
        .map_err(|error| error.to_string())?;
    let mut rows = statement.query([]).map_err(|error| error.to_string())?;
    while let Some(row) = rows.next().map_err(|error| error.to_string())? {
        let source_key: String = row.get(0).map_err(|error| error.to_string())?;
        let generation_idx: i64 = row.get(1).map_err(|error| error.to_string())?;
        result.source_keys.insert(source_key.clone());
        if live_source_keys.contains(&source_key) {
            result
                .generation_ids_by_source
                .entry(source_key.clone())
                .or_default()
                .insert(generation_idx);
        }
        result.generations_scanned = result.generations_scanned.saturating_add(1);

        let valid: i64 = row.get(8).map_err(|error| error.to_string())?;
        if valid != 1 {
            let oversized: i64 = row.get(9).map_err(|error| error.to_string())?;
            if oversized == 1 {
                result.skipped_large_records = result.skipped_large_records.saturating_add(1);
            }
            continue;
        }

        let model: Option<String> = row.get(2).map_err(|error| error.to_string())?;
        let input_tokens: Option<String> = row.get(3).map_err(|error| error.to_string())?;
        let output_tokens: Option<String> = row.get(4).map_err(|error| error.to_string())?;
        let cached_tokens: Option<String> = row.get(5).map_err(|error| error.to_string())?;
        let total_tokens: Option<String> = row.get(6).map_err(|error| error.to_string())?;
        let timestamp_seconds: Option<i64> = row.get(7).map_err(|error| error.to_string())?;
        let Some(model) = model else {
            continue;
        };
        let Some(input_tokens) = input_tokens.and_then(|value| value.parse::<u64>().ok()) else {
            continue;
        };
        let Some(output_tokens) = output_tokens.and_then(|value| value.parse::<u64>().ok()) else {
            continue;
        };
        let Some(cached_tokens) = cached_tokens.and_then(|value| value.parse::<u64>().ok()) else {
            continue;
        };
        let Some(total_tokens) = total_tokens.and_then(|value| value.parse::<u64>().ok()) else {
            continue;
        };
        let Some(timestamp_seconds) = timestamp_seconds else {
            continue;
        };
        let event = GenerationEvent {
            model,
            input_tokens,
            output_tokens,
            cached_tokens,
            total_tokens,
            timestamp_seconds,
        };

        let Some(date_time) = Local.timestamp_opt(event.timestamp_seconds, 0).single() else {
            continue;
        };
        if date_time.date_naive() >= since {
            result.events.push(event);
        }
    }

    Ok(result)
}

fn scan_database(
    path: &Path,
    since: NaiveDate,
    archived_generation_ids: &HashSet<i64>,
) -> Result<DatabaseScanResult, String> {
    let connection = Connection::open_with_flags(path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .map_err(|error| error.to_string())?;
    connection
        .busy_timeout(std::time::Duration::from_secs(2))
        .map_err(|error| error.to_string())?;

    let mut columns = connection
        .prepare("SELECT name FROM pragma_table_info('steps')")
        .map_err(|error| error.to_string())?;
    let step_columns = columns
        .query_map([], |row| row.get::<_, String>(0))
        .map_err(|error| error.to_string())?
        .collect::<Result<HashSet<_>, _>>()
        .map_err(|error| error.to_string())?;

    // `gen_metadata.idx` and `steps.idx` are separate sequences. The
    // generation metadata rows correspond to the ordered type-15 generation
    // steps, not to a step with the same numeric idx.
    let step_records = if step_columns.contains("metadata") && step_columns.contains("step_type") {
        let status_column = if step_columns.contains("status") {
            "status"
        } else {
            "NULL"
        };
        let payload_column = if step_columns.contains("step_payload") {
            "CASE WHEN length(step_payload) <= 1048576 THEN step_payload ELSE NULL END"
        } else {
            "NULL"
        };
        let mut statement = connection
            .prepare(&format!(
                "SELECT CASE WHEN length(metadata) <= 65536 THEN metadata ELSE NULL END,
                        {status_column}, {payload_column}
                 FROM steps
                 WHERE step_type = ?1
                 ORDER BY idx"
            ))
            .map_err(|error| error.to_string())?;
        let rows = statement
            .query_map([GENERATION_STEP_TYPE], |row| {
                let metadata: Option<Vec<u8>> = row.get(0)?;
                let status: Option<i64> = row.get(1)?;
                let payload: Option<Vec<u8>> = row.get(2)?;
                let timestamp = metadata.as_deref().and_then(step_timestamp);
                let text_complete = performance::is_completed_text(status, payload.as_deref());
                Ok((timestamp, text_complete))
            })
            .map_err(|error| error.to_string())?;
        let mut records = Vec::new();
        for row in rows {
            records.push(row.map_err(|error| error.to_string())?);
        }
        records
    } else {
        Vec::new()
    };

    let query = "SELECT idx, data, length(data)
                 FROM gen_metadata
                 WHERE data IS NOT NULL
                 ORDER BY idx";

    let mut statement = connection
        .prepare(query)
        .map_err(|error| error.to_string())?;
    let mut rows = statement.query([]).map_err(|error| error.to_string())?;
    let mut events = Vec::new();
    let mut performance_samples = Vec::new();
    let source = path.parent().and_then(Path::parent)
        .and_then(Path::file_name).and_then(|name| name.to_str())
        .unwrap_or("antigravity");
    let mut generations_scanned = 0_u64;
    let mut skipped_large_records = 0_u64;
    let mut generation_ordinal = 0_usize;

    while let Some(row) = rows.next().map_err(|error| error.to_string())? {
        let generation_idx: i64 = row.get(0).map_err(|error| error.to_string())?;
        let current_ordinal = generation_ordinal;
        generation_ordinal = generation_ordinal.saturating_add(1);
        let archived = archived_generation_ids.contains(&generation_idx);
        if !archived {
            generations_scanned = generations_scanned.saturating_add(1);
        }
        let blob_size: i64 = row.get(2).map_err(|error| error.to_string())?;
        if blob_size > MAX_GENERATION_BLOB_BYTES {
            if !archived {
                skipped_large_records = skipped_large_records.saturating_add(1);
            }
            continue;
        }

        let blob: Vec<u8> = row.get(1).map_err(|error| error.to_string())?;
        let (step_timestamp, text_complete) = step_records.get(current_ordinal)
            .copied().unwrap_or((None, false));
        if text_complete {
            if let Some(sample) = performance::sample(&blob, step_timestamp, source) {
                performance_samples.push(sample);
            }
        }
        if archived {
            continue;
        }
        let Some(event) = generation_event(&blob, step_timestamp) else {
            continue;
        };

        let Some(date_time) = Local.timestamp_opt(event.timestamp_seconds, 0).single() else {
            continue;
        };
        if date_time.date_naive() >= since {
            events.push(event);
        }
    }

    Ok(DatabaseScanResult {
        events,
        performance_samples,
        generations_scanned,
        skipped_large_records,
    })
}

fn discover_database_files() -> Result<Vec<PathBuf>, String> {
    let Some(home) = dirs::home_dir() else {
        return Err("无法定位用户目录".to_string());
    };
    let gemini_home = home.join(GEMINI_DIR);
    if !gemini_home.exists() {
        return Ok(Vec::new());
    }

    let mut paths = Vec::new();
    let entries = fs::read_dir(&gemini_home).map_err(|error| error.to_string())?;
    for entry in entries {
        let entry = entry.map_err(|error| error.to_string())?;
        let file_name = entry.file_name();
        let file_name = file_name.to_string_lossy();
        if !file_name.starts_with(ANTIGRAVITY_PREFIX) || !entry.path().is_dir() {
            continue;
        }

        let conversations_dir = entry.path().join("conversations");
        let Ok(conversation_entries) = fs::read_dir(&conversations_dir) else {
            continue;
        };
        for conversation_entry in conversation_entries {
            let conversation_entry = conversation_entry.map_err(|error| error.to_string())?;
            let path = conversation_entry.path();
            if path.extension().and_then(|extension| extension.to_str()) != Some("db") {
                continue;
            }
            paths.push(fs::canonicalize(&path).unwrap_or(path));
        }
    }

    paths.sort();
    paths.dedup();
    Ok(paths)
}

fn decode_varint(bytes: &[u8], offset: usize) -> Option<(u64, usize)> {
    if offset >= bytes.len() {
        return None;
    }

    let mut value = 0_u64;
    for byte_index in 0..10 {
        let position = offset.checked_add(byte_index)?;
        let byte = *bytes.get(position)?;
        let payload = u64::from(byte & 0x7f);
        if byte_index == 9 && payload > 1 {
            return None;
        }
        value |= payload << (byte_index * 7);
        if byte & 0x80 == 0 {
            return Some((value, position + 1));
        }
    }
    None
}

fn field<'a>(requested: u32, bytes: &'a [u8]) -> Option<WireValue<'a>> {
    let mut offset = 0;
    while offset < bytes.len() {
        let (tag, tag_end) = decode_varint(bytes, offset)?;
        let number = u32::try_from(tag >> 3).ok()?;
        if number == 0 {
            return None;
        }

        match tag & 0x7 {
            0 => {
                let (value, value_end) = decode_varint(bytes, tag_end)?;
                if number == requested {
                    return Some(WireValue::Varint(value));
                }
                offset = value_end;
            }
            1 | 5 => {
                let width = if tag & 0x7 == 1 { 8 } else { 4 };
                offset = tag_end.checked_add(width)?;
                if offset > bytes.len() {
                    return None;
                }
            }
            2 => {
                let (length, length_end) = decode_varint(bytes, tag_end)?;
                let length = usize::try_from(length).ok()?;
                let end = length_end.checked_add(length)?;
                if end > bytes.len() {
                    return None;
                }
                if number == requested {
                    return Some(WireValue::Bytes(&bytes[length_end..end]));
                }
                offset = end;
            }
            _ => return None,
        }
    }
    None
}

fn bytes_field(number: u32, bytes: &[u8]) -> Option<&[u8]> {
    match field(number, bytes)? {
        WireValue::Bytes(value) => Some(value),
        WireValue::Varint(_) => None,
    }
}

fn varint_field(number: u32, bytes: &[u8]) -> Option<u64> {
    match field(number, bytes)? {
        WireValue::Varint(value) => Some(value),
        WireValue::Bytes(_) => None,
    }
}

fn string_field(number: u32, bytes: &[u8]) -> Option<String> {
    let value = bytes_field(number, bytes)?;
    let value = std::str::from_utf8(value).ok()?.trim();
    (!value.is_empty()).then(|| value.to_string())
}

fn timestamp_seconds(message: &[u8]) -> Option<i64> {
    let seconds = varint_field(1, message)?;
    let seconds = i64::try_from(seconds).ok()?;
    (seconds > 0).then_some(seconds)
}

fn step_timestamp(step_metadata: &[u8]) -> Option<i64> {
    bytes_field(1, step_metadata).and_then(timestamp_seconds)
}

fn generation_event(blob: &[u8], step_timestamp: Option<i64>) -> Option<GenerationEvent> {
    let wrapped = bytes_field(1, blob)?;
    let model_id = string_field(19, wrapped);
    let label = string_field(21, wrapped);
    let usage = bytes_field(4, wrapped)?;

    let system_prompt_tokens = varint_field(1, usage).unwrap_or(0);
    let raw_input_tokens = varint_field(2, usage).unwrap_or(0);
    let output_tokens = varint_field(3, usage).unwrap_or(0);
    let cached_tokens = varint_field(5, usage).unwrap_or(0);
    let input_tokens = system_prompt_tokens.checked_add(raw_input_tokens)?;
    let generated = raw_input_tokens != 0 || output_tokens != 0 || cached_tokens != 0;

    if (model_id.is_none() && label.is_none() && !generated) || (!generated && input_tokens == 0) {
        return None;
    }

    let embedded_timestamp = bytes_field(9, wrapped)
        .and_then(|timing| bytes_field(4, timing))
        .and_then(timestamp_seconds);
    let timestamp_seconds = embedded_timestamp.or(step_timestamp)?;
    let total_tokens = input_tokens
        .checked_add(cached_tokens)?
        .checked_add(output_tokens)?;

    Some(GenerationEvent {
        model: label.or(model_id).unwrap_or_else(|| "未知模型".to_string()),
        input_tokens,
        output_tokens,
        cached_tokens,
        total_tokens,
        timestamp_seconds,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn varint(value: u64) -> Vec<u8> {
        let mut value = value;
        let mut result = Vec::new();
        loop {
            let mut byte = (value & 0x7f) as u8;
            value >>= 7;
            if value != 0 {
                byte |= 0x80;
            }
            result.push(byte);
            if value == 0 {
                return result;
            }
        }
    }

    fn bytes_field(number: u32, value: &[u8]) -> Vec<u8> {
        let mut result = varint(u64::from(number << 3 | 2));
        result.extend(varint(value.len() as u64));
        result.extend(value);
        result
    }

    fn varint_field(number: u32, value: u64) -> Vec<u8> {
        let mut result = varint(u64::from(number << 3));
        result.extend(varint(value));
        result
    }

    fn generation_blob() -> Vec<u8> {
        let usage = [
            varint_field(1, 100),
            varint_field(2, 200),
            varint_field(3, 30),
            varint_field(5, 50),
        ]
        .concat();
        let timestamp = varint_field(1, 1_800_000_000);
        let timing = bytes_field(4, &timestamp);
        let wrapped = [
            bytes_field(4, &usage),
            bytes_field(9, &timing),
            bytes_field(19, b"gemini-3.8-flash-high"),
            bytes_field(21, "Gemini 3.8 Flash (High)".as_bytes()),
        ]
        .concat();
        bytes_field(1, &wrapped)
    }

    #[test]
    fn recent_day_ranges_include_today_and_exclude_the_day_before_the_range() {
        let today = NaiveDate::from_ymd_opt(2026, 9, 26).expect("date should be valid");
        assert!(is_within_last_days(today, today, 3));
        assert!(is_within_last_days(today - Duration::days(2), today, 3));
        assert!(!is_within_last_days(today - Duration::days(3), today, 3));
        assert!(!is_within_last_days(today + Duration::days(1), today, 3));
    }

    #[test]
    fn decodes_native_generation_usage() {
        let event = generation_event(&generation_blob(), None).expect("generation should decode");
        assert_eq!(event.model, "Gemini 3.8 Flash (High)");
        assert_eq!(event.input_tokens, 300);
        assert_eq!(event.output_tokens, 30);
        assert_eq!(event.cached_tokens, 50);
        assert_eq!(event.total_tokens, 380);
        assert_eq!(event.timestamp_seconds, 1_800_000_000);
    }

    #[test]
    fn reads_archived_usage_and_skips_the_same_live_generation() {
        let directory = tempfile::tempdir().expect("temporary directory should be created");
        let live_path = directory.path().join("conversation.db");
        let archive_path = directory.path().join("token_usage_archive.db");
        let source_key = "antigravity/conversations/test.db";
        let blob = generation_blob();

        let live = Connection::open(&live_path).expect("live database should open");
        live.execute_batch(
            "CREATE TABLE gen_metadata (idx INTEGER PRIMARY KEY, data BLOB NOT NULL);
             CREATE TABLE steps (idx INTEGER PRIMARY KEY, step_type INTEGER, metadata BLOB);
             INSERT INTO steps (idx, step_type, metadata) VALUES (1, 15, NULL);",
        )
        .expect("live database schema should be created");
        live.execute(
            "INSERT INTO gen_metadata (idx, data) VALUES (?1, ?2)",
            rusqlite::params![7_i64, &blob],
        )
        .expect("live generation should be inserted");
        drop(live);

        let archive = Connection::open(&archive_path).expect("archive database should open");
        archive
            .execute_batch(
                "CREATE TABLE archived_sources (
                    source_key TEXT PRIMARY KEY,
                    archived_at INTEGER NOT NULL,
                    generation_count INTEGER NOT NULL
                 );
                 CREATE TABLE archived_generations (
                    source_key TEXT NOT NULL,
                    generation_idx INTEGER NOT NULL,
                    ordinal INTEGER NOT NULL,
                    model TEXT,
                    input_tokens TEXT,
                    output_tokens TEXT,
                    cached_tokens TEXT,
                    total_tokens TEXT,
                    timestamp_seconds INTEGER,
                    valid INTEGER NOT NULL,
                    oversized INTEGER NOT NULL,
                    PRIMARY KEY (source_key, generation_idx)
                 );",
            )
            .expect("archive schema should be created");
        archive
            .execute(
                "INSERT INTO archived_sources VALUES (?1, ?2, ?3)",
                rusqlite::params![source_key, 1_i64, 1_i64],
            )
            .expect("archive source should be inserted");
        archive
            .execute(
                "INSERT INTO archived_generations VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)",
                rusqlite::params![
                    source_key,
                    7_i64,
                    0_i64,
                    "Gemini 3.8 Flash (High)",
                    "300",
                    "30",
                    "50",
                    "380",
                    1_800_000_000_i64,
                    1_i64,
                    0_i64
                ],
            )
            .expect("archived generation should be inserted");
        drop(archive);

        let since = NaiveDate::from_ymd_opt(2026, 1, 1).expect("date should be valid");
        let live_source_keys = HashSet::from([source_key.to_string()]);
        let archived =
            scan_archive(&archive_path, since, &live_source_keys).expect("archive should scan");
        assert_eq!(archived.generations_scanned, 1);
        assert_eq!(archived.events.len(), 1);
        assert_eq!(archived.events[0].total_tokens, 380);
        assert!(archived.source_keys.contains(source_key));

        let live = scan_database(
            &live_path,
            since,
            archived
                .generation_ids_by_source
                .get(source_key)
                .expect("archive should retain the source row id"),
        )
        .expect("live database should scan");
        assert_eq!(live.generations_scanned, 0);
        assert!(live.events.is_empty());
    }

    #[test]
    fn uses_step_timestamp_when_embedded_timestamp_is_missing() {
        let usage = [varint_field(2, 10), varint_field(3, 5)].concat();
        let wrapped = [bytes_field(4, &usage), bytes_field(19, b"gemini-test")].concat();
        let blob = bytes_field(1, &wrapped);
        let event = generation_event(&blob, Some(1_800_000_123)).expect("fallback should decode");
        assert_eq!(event.timestamp_seconds, 1_800_000_123);
    }

    #[test]
    fn ignores_zero_value_bookkeeping_rows() {
        let usage = varint_field(1, 100);
        let wrapped = bytes_field(4, &usage);
        let blob = bytes_field(1, &wrapped);
        assert!(generation_event(&blob, Some(1_800_000_000)).is_none());
    }
}
